[package]
name = "wantyougone"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
csv = "1.3.1"
image = "0.25.5"
rand = "0.8.5"
ratatui = "0.29.0"
ratatui-image = "3.0.0"
rodio = "0.20.1"
